export default Object.freeze({
  WELCOME_SCREEN: "WelcomeScreen",
  LOGIN_SCREEN: "LoginScreen",
  REGISTER_SCREEN: "RegisterScreen",
  AUTH_NAVIGATION: "Auth Nav",
  TAB_NAVIGATION: "Tab Nav",
  HOME_SCREEN: "Home Screen",
  ACCOUNT_SCREEN: "Account Screen",
  SEARCH_SCREEN: "Seach Screen",
  PROFILE_SCREEN: "Profile Screen",
  USER_NAVIGATION: "User nav",
  ORDERS_HISTORY_SCREEN: "Orders Screen",
  ORDERS_DETAIL_SCREEN: "OrderDetail Screen",
  PENDING_ORDERS_SCREEN: "Pending Screen",
  TRACK_DELIVERY_SCREEN: "TrackDelivery Screen",
  ORDER_NAVIGATION: "Order Nav",
  ORDER_SCREEN: "Order Screen",
  CHECHOUT_SCREEN: "Checkout Screen",
  TRANSACTIONS_SCREEN: "Transactions Screen",
  PROFILE_VIEW_SCREEN: "Profile view Screen",
  PAYMENT_SCREEN: "Payment Screen",
  ACTION_MENU_SCREEN: "Menu Screen",
  FORMS_NAVIGATION: "Forms Nav",
  FORMS_ACCOUNT_FORM: "Accounts Form",
  FORMS_PROFILE_FORM: "Profile Form",
  FORMS_NEXT_OF_KEEN_FORM: "NextOfKeen Form",
});
